^NumLock::pause
!NumLock::numpadclear
<#NumLock::#pause
>#NumLock::#pause
NumpadDiv::^z
^NumpadDiv::numpaddiv
!NumpadDiv::^numpad1
<#NumpadDiv::launch_app1
>#NumpadDiv::launch_app1
NumpadMult::^y
^NumpadMult::numpadmult
!NumpadMult::^numpad2
<#NumpadMult:: Run "C:\Users\%A_UserName%"&&"C:\Users\" A_UserName ""
>#NumpadMult:: Run "C:\Users\%A_UserName%"&&"C:\Users\" A_UserName ""
NumpadSub::^s
^NumpadSub::numpadsub
!NumpadSub::^numpad3
<#NumpadSub::launch_app2
>#NumpadSub::launch_app2
NumpadAdd::^a
^NumpadAdd::numpadadd
!NumpadAdd::^numpad4
^NumpadEnter::^numpad5
!NumpadEnter::!numpad5
NumpadDel::numpaddel
NumpadDot::^!+right
!NumpadDel::^numpad6
!NumpadDot::^numpad6
NumpadIns::^c
Numpad0::^!+left
!NumpadIns::^numpad7
!Numpad0::^numpad7
NumpadEnd::volume_down
Numpad1::!+down
!NumpadEnd::f13
!Numpad1::f13
NumpadDown::^x
Numpad2::^!left
!NumpadDown::f14
!Numpad2::f14
NumpadPgDn::^v
Numpad3::^!right
!NumpadPgDn::f15
!Numpad3::f15
NumpadLeft::volume_up
Numpad4::!+up
!NumpadLeft::f16
!Numpad4::f16
NumpadClear::volume_mute
Numpad5::^+left
!NumpadClear::f17
!Numpad5::f17
NumpadRight::^f
Numpad6::^+right
!NumpadRight::f18
!Numpad6::f18
NumpadHome::!+left
Numpad7::!+left
!NumpadHome::f19
!Numpad7::f19
NumpadUp::!+space
Numpad8::!+space
!NumpadUp::f20
!Numpad8::f20
NumpadPgUp::!+right
Numpad9::!+right
!NumpadPgUp::f21
!Numpad9::f21
PrintScreen::f22
^PrintScreen::^printscreen
!PrintScreen::!printscreen
<#PrintScreen::^numpad8
>#PrintScreen::^numpad8
ScrollLock::f23
^ScrollLock::ctrlbreak
!ScrollLock::scrolllock
<#ScrollLock::^numpad9
>#ScrollLock::^numpad9
Pause::f24
^Pause::ctrlbreak
!Pause::pause
<#Pause::#pause
>#Pause::#pause
